### ISSUE TITLE
Error when invoiceFor a user

### ISSUE THREAD

**Issue by yebor974** [OFFLINE-GmbH/oc-cashier-plugin#8] opened 2019-03-14 12:26 UTC
Hi,

After using this plugin to charge and invoice my user, i have a issue with preferredCurrency function in classes/Billable.php 

`public function preferredCurrency()
{
        return Cashier::usesCurrency();
}`

This function uses Cashier but it's not defined in uses section, therefore returns this error 

> Class 'OFFLINE\Cashier\Classes\Cashier' not found" on line 578 of D:\perso\projects\UCUH\site\plugins\offline\cashier\classes\Billable.php

**Comment by Adrion** [comment] 2019-03-14 14:47
I made a fork of this plugin and yes I got the issue too. 
@tobias-kuendig can you confirm the issue ? 

If confirmed a simple `use Laravel\Cashier\Cashier;` will fix it 😄

**Comment by tobias-kuendig** [comment] 2019-03-18 06:46
Yes, this of course is a bug because of the missing import. Fixed in 0056f0c and released as 1.0.6. Thanks @yebor974 	and @Adrion

**Closed by tobias-kuendig** 2019-03-18 06:46 UTC
